apiVersion: v1
kind: Service
metadata:
  name: my-website-service
spec:
  selector:
    app: website  # заміни на свій
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
